import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#1d1b18",
        tertiary: "#09685d",
        "surface-container-high": "#eee7e2",
        "on-primary-container": "#ffffff",
        secondary: "#6B7280",
        "surface-white": "#FFFFFF",
        primary: "#22C55E",
        "primary-fixed": "#DCFCE7",
        "surface-container-highest": "#e8e1dc",
        "error-container": "#ffdad6",
        "surface-variant": "#e8e1dc",
        error: "#ba1a1a",
        "surface-container": "#f3ede8",
        "tertiary-container": "#308176",
        "teal-custom": "#308176",
        "surface-container-low": "#f9f2ed",
        "on-surface-variant": "#424752",
        danger: "#E63946",
        surface: "#ffffff",
        "surface-container-lowest": "#ffffff",
        "border-muted": "#EAE2DC",
        "outline-variant": "#c2c6d4",
        "primary-container": "#16A34A",
        "secondary-container": "#e5ded9",
        outline: "#727784",
        background: "#FFFFFF",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#004491",
        "surface-tint": "#15803D",
        "surface-bright": "#fcf8fb",
        "inverse-surface": "#303032",
        ink: "#111111",
        "on-surface": "#111111",
        "on-secondary-fixed-variant": "#494643",
        "on-secondary-fixed": "#1d1b18",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "8px",
        "margin-mobile": "16px",
        lg: "24px",
        md: "16px",
        sm: "12px",
        unit: "4px",
        xl: "32px",
        "margin-desktop": "48px",
        "margin-tablet": "32px",
        gutter: "16px",
      },
      fontFamily: {
        sans: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "display-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "currency-display": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
